security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
   
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    
    role_hierarchy:
        ROLE_ASSISTANT: ROLE_USER
        ROLE_DOCTOR: ROLE_USER
        ROLE_ADMIN: [ROLE_DOCTOR, ROLE_ASSISTANT, ROLE_USER]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator
            logout:
                path: app_logout
                
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/admin1, roles: ROLE_ADMIN }
        - { path: ^/doctor, roles: ROLE_DOCTOR }
        - { path: ^/assistant, roles: ROLE_ASSISTANT }
        # - { path: ^/user, roles: ROLE_USER }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }        
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 
                time_cost: 3 
                memory_cost: 10